### ISSUE TITLE
/lib64/libc.so.6 Error!

### ISSUE THREAD

**Issue by malshikh** [ibme-qubic/oxford_asl#2]
Hi,
I can't use this version!! oxford_asl output the following error:
asl_file: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by asl_file)

Any suggestions?!

**Comment by boegel** [comment]
disclaimer: I'm not a maintainer for this project

The version you downloaded was built for a more recent version of `glibc` than the one you have.

Which OS are you using, and which version did you download?

**Comment by mcraig-ibme** [comment]
Closing historical issue
