### ISSUE TITLE
How to install/ overwrite previous version in MACOS

### ISSUE THREAD

**Issue by Fionayjx** [ibme-qubic/oxford_asl#4]
Hi, 
I am not familiar with the programing.
A basic question here.
After I downloaded the newest release of BASIL, how do I overwrite the previous version in existing FSL 5.0.10 in MACos?

Thanks

**Comment by pallavinair** [comment]
Hi 

I need to use BASIL for my PhD Thesis Analysis

I downloaded the Source Code from https://github.com/ibme-qubic/oxford_asl/releases

I wanted to know how do I install the newest release of BASIL  in Mac OS or Ubuntu.?

Thanks

**Comment by mcraig-ibme** [comment]
Hi, apologies for the lack of response, I have not been getting GitHub notifications and a number of issues have been raised here without me realising.

Updated versions of oxford_asl and basil are available in FSL 6.0.1 and later - if you still have this issue please try upgrading FSL and remove any previous releases of BASIL.

**Comment by mcraig-ibme** [comment]
Closing historical issue
