### ISSUE TITLE
Where to install BASIL

### ISSUE THREAD

**Issue by Rosenberg78** [ibme-qubic/oxford_asl#7]
Hello.
I have a linux with Ubuntu 18 and FSL 5 installed. I want to use BASIL which i downloaded  (Version for Ubuntu 16) and installed to  my home directory. It opens but I cant preview the images and gives errors when load data to tun it

ERROR:: Environment variable FSLOUTPUTTYPE is not set!
Please make sure that the appropriate configuration file is sourced by your shell (e.g. by putting it in .profile).
e.g. bash or sh users add the line ". ${FSLDIR}/etc/fslconf/fsl.sh"

Return code: 1

Thank for your help
Jens

**Comment by Rosenberg78** [comment]
Update:
I installed FSL 6 and can now update the image in the asl_gui. The processing is still not running correctly and gives several of errors. Seems like it is looking for or cant access some files. Should I place the Basil folder somewhere or run some commands to install Basil with FSL? Below are some of the error. I have wxpython, matplotlib, numpy and nibabel installed
Thanks for your help
Jens

  Voxel data not found: /tmp/fsl_AxHdb8_ox_asl/mask (File is invalid or does not exist)
FabberRunDataNewimage::Loading mask data from '/tmp/fsl_AxHdb8_ox_asl/mask'
Exception caught in fabber:
  Voxel data not found: /tmp/fsl_AxHdb8_ox_asl/mask (File is invalid or does not exist)
Could not find a supported file with prefix "/tmp/fsl_AxHdb8_ox_asl/basil/step2/finalMVN"
/home/rosenberg/Basil/oxford_asl-3.9.22-ubuntu16/oxford_asl/basil: 74: /home/rosenberg/Basil/oxford_asl-3.9.22-ubuntu16/oxford_asl/basil: cannot create /tmp/fsl_AxHdb8_ox_asl/basil/step2/info.txt: Directory nonexistent
End.
ls: cannot access '/tmp/fsl_AxHdb8_ox_asl/basil/step?': No such file or directory
fslmaths: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
fslmaths: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
Fabber variance calculator
Working in -m
cat: invalid option -- 'm'

**Comment by mcraig-ibme** [comment]
Hi, apologies for the lack of response, I have not been getting GitHub notifications and a number of issues have been raised here without me realising.

I note that this issue is very old and looks related to the lack of libopenblas by default on Ubuntu. If you have now solved this, do let me know so I can close the issue.

**Comment by mcraig-ibme** [comment]
Closing historical issue

**Comment by acamargofb** [comment]
I don't have BASIL install, how can I install it? I have installed fsl already
